### PR TITLE
[merge] Changing school selection to drop down

### LINKED ISSUE #5: EPIC: Refactor Course create/edit to use dropdown for schools
### Discussion

If you go to the course page, and click create you will see a field where you can enter school for the course.

However, we also have a place where we enter information about schools.  We don't want users to be able to put "just anything" in the schools field like they can now.  Instead, they should have a dropdown menu with just the schools that have already been entered into the system. School values are things like UCSB, WSU, OSU, UW-Hilo, etc.

What we want is to "get all" schools from the schools API, build a drop down menu from those results, and use that select from all the already created schools when creating or editing a course.

### Acceptance Criteria

- [x] #10

# Implementation Todos

- [ ] #11

You can look and learn how to create and implement the dropdown from <https://courses.dokku-00.cs.ucsb.edu/>. As you can see if you hover over the quarter you can see the drop-down list.   You can use the storybook to explore how these dropdown work.  

There are also other drop downs, such as the one in the model for personal schedules, that are populated from lists (this is more like what you are bulding.)

In this first issue, JUST focus on creating that one React component, along with fixtures for the schools, storybook story, and tests.   You'll then use it later when refactoring the form.

- [ ] #12

You can go to the courses repo and see how the dropdown is used on the modal for adding courses to a personal schedule, or when searching for courses.

### PR DESCRIPTION
**Pull request by yuxiaolejs**
In this PR, I changed the school selection in course create/edit pages to use drop down.

Dokku dev deployment available here: https://organic-yuxiaolejs-gha.dokku-11.cs.ucsb.edu/

It looks like:
image

Story here: https://ucsb-cs156-s24.github.io/proj-organic-s24-5pm-3/prs/50/storybook/?path=/story/components-courses-coursesform--create (Not working since no data provided by backend)

Closes #5

### CODE REVIEW

**Review by tmcanepa — APPROVED** [review]
LGTM

**Comment by sanilkatula** [comment]
Does this PR only have a story book? Change the heading of the PR accordingly.
you can feed the data through Swagger and test if the frontend is working.

**Comment by sanilkatula** [comment]
Screenshot 2024-05-30 at 5 05 02 PM

it does not work.

**Comment by yuxiaolejs** [comment]
> Does this PR only have a story book? Change the heading of the PR accordingly. you can feed the data through Swagger and test if the frontend is working.

Oh, I mean the storybook is not working... The stage deployment is working now and I am feeding data so that you can test it alive.

**Comment by yuxiaolejs** [comment]
@pconrad Sorry for lying to you... It's all fixed now! I have fed some data by directing inserting into the DB so that you can test it.

**Comment by pconrad** [comment]
> @pconrad Sorry for lying to you... It's all fixed now! I have fed some data by directing inserting into the DB so that you can test it.

You didn't exactly "lie" ... maybe at most you were "careless with the truth".  I apologize for using that word.    

The point is: if your PR description says that the deployment is for that branch, you need to freeze that deployment until the PR is merged.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
