### PR TITLE
Created Course Show Page with Storybook Page

### PR DESCRIPTION
**Pull request by tmcanepa**
I created the Course Show Page which displays an individual courses' information as displayed on the index page.. It has yet to be linked in the App.js page and on dokku but here is the storybook demonstration of how it would look.
image

### CODE REVIEW

**Review by Xalex217 — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
There are two choices:
* Make this a storybook only PR, in which case you should not be modifying the CoursesTable.js and CoursesTable.tests.js for the hyperlink (which is currently going to be a dead link).  That's worth 10 points, and then you can link to it from the other in another 10 point PR.
* OR: you need to go all the way in this PR and add the route into App.js, plus make a dokku deployment.  That only gets you 10 points total for everything but it might be the easier route.

The problem with this PR the way is stands right now is that it introduces a bug: you have a hyperlink now on the CoursesIndex page that goes to a non-existing show page.

That's not ok.  We avoid merging things into main that are "half cooked" and lead the user to have Page Not Found errors.

Can you choose one direction or the other and modify this PR accordingly?  Either way is fine with me, but the current PR is not mergable.

One other note: because you have a white space only change in a backend file, this PR triggers all of the backend mutation testing. That's slowing you down.  You might want to restore that file to how it is on the main branch to avoid that.

**Review by 30912hyl — APPROVED** [review]
the code LGTM, could you link the storybook/dev deployment for testing?

**Review by pconrad — APPROVED** [review]
LGTM!  Nice and clean, a pure storybook PR.  Easy to merge!

**Review by pconrad — CHANGES_REQUESTED** [review]
Just one problem: the storybook isn't showing any data for the course.

https://ucsb-cs156-s24.github.io/proj-organic-s24-5pm-3/prs/53/storybook/?path=/story/pages-courseshowpage--default

Can you fix this?

**Review by pconrad — CHANGES_REQUESTED** [review]
Code looks nice and clean, but the storybook is empty.

Hints on the slack channel here: https://ucsb-cs156-s24.slack.com/archives/C06S21ENK5X/p1717195583242529  (not just that post but the entire thread that follows.)

**Comment by tmcanepa** [comment]
Im not super sure what the problem with the storybook is because when I run it locally it shows up fine with npm run storybook but for some reason, when you open it through GitHub the course no longer appears

**Review by pconrad — APPROVED** [review]
Merging with known problem in storybook; the entry for CourseShowPage.stories.js is working on localhost but not on Github Pages.  Not sure why.

**Pull request merged**
