### PR TITLE
Aaron Delete School button

### PR DESCRIPTION
**Pull request by Xalex217**
Before: When a school  is added (for right now this needs to be done manually through swagger), a school appears in a table with edit. 
After: Now, when a school is added, there is a delete button that appears next to edit. This gives us the ability to delete the school from the table. 

EDIT: https://organic-xalex217.dokku-11.cs.ucsb.edu/admin/schools
Schools must be added using swagger for right now, as the add school button was not finished at the time I completed the delete button.

### CODE REVIEW

**Comment by yuxiaolejs** [comment]
Please do not commit your stryker files into the repo.

**Review by yuxiaolejs — CHANGES_REQUESTED** [review]
Please do not commit your stryker files into the repo.

**Review by yuxiaolejs — DISMISSED** [review]
LGTM

**Review by 30912hyl — DISMISSED** [review]
LGTM

**Comment by sanilkatula** [comment]
Please send a deployment link, so that we can actually check if the desired functionality is working or not.

**Review by pconrad — CHANGES_REQUESTED** [review]
The title of this PR is "Aaron end button".  

I don't know what I'm supposed to take away from that.  There's no "end" button that I'm aware of.

And it's also not clear what the purpose of this PR is... what actually changes here?

I'm marking this as a draft PR until it is more clear.

**Review by pconrad — CHANGES_REQUESTED** [review]
The PR description says this:

image


I'm not sure what to make of that.  There needs to be a clear "before" and "after" where the PR actually adds some improvement in functionality to the running app that can be demonstrated.  I don't see what that is, here, and the comment above about how it can't be tested seems to confirm that maybe there isn't one?

Help me understand what your intentions are.

**Comment by yuxiaolejs** [comment]
@Xalex217 Bro add me as admin so that I can CR for you!

**Comment by sanilkatula** [comment]
Make all the staff admin.

**Review by yuxiaolejs — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
I'm reluctantly merging this without checking the integration with the previous PR; the deployment here had a broken Edit button (while the other PR had a broken delete button, which this one, we hope, fixes.)

I guess we'll see.

**Review by tmcanepa — APPROVED** [review]
LGTM

**Pull request merged**
