### PR TITLE
[feat] GitHub App integration

### LINKED ISSUE #15: [feat] Instructor can install GithubApp
# Acceptance criteria
- [x] There's a documented (in `/docs` of the repo) process by which the developer of ProjOrganic can set up a Github App
- [x] There is a defined process by which an instructor can authorize the GitHub App to invite users to the GitHub Organization.
- [ ] There is a demonstration of how a student on the course roster can log in and see a list of the courses they are students for and can click join to join any one of them.

### PR DESCRIPTION
**Pull request by yuxiaolejs**
In this PR, I added code to enable organic to function as a Github App. By doing so, instructors now can link our github app to their course, which in current stage, can invite their students to the course organization automatically

## New contents

Backend now is integrated with github app, you can interact with it using:
- `GitHubUserApi` bean is used to authenticate as the user is logged in.
- `GitHubApp` bean is used to authenticate as a github app.
- `GitHubToken` bean exposes the Oauth token of the current user, you can use it to call github apis manually.

From now on, this system works with Github App instead of Oauth app, and I have provided a documentation on setting in up in the [docs/oauth.md](docs/oauth.md) **You MUST have a private key configured to make it work!**

One new page is added, and it looks like this:

image

One static page is added, and it looks like this:

image

You can find it [here](https://ucsb-cs156-s24.github.io/proj-organic-s24-5pm-3/prs/23/storybook/?path=/story/pages-courses-coursejoinpage--default) in the storybook, but it's not quite working since it depends on back end data.

I have a staged build for you to test it. You can find it here: https://organic.dokku.tianleyu.com/

For a dokku dev deployment, please see here: https://organic-yuxiaolejs-dev.dokku-11.cs.ucsb.edu/

## Limitations
Now this **DOES NOT** support roster check, meaning that a student can be added without being on the roster. This is because we haven't implemented the methods for instructors to import their roster, and haven't finalized the table we will need to store the roster. This feature will be added as a part of the roster management PR.

Closes #15

### CODE REVIEW

**Comment by yuxiaolejs** [comment]
All fixed

**Comment by sanilkatula** [comment]
Please make all the staff an admin user.

**Comment by yuxiaolejs** [comment]
> Please make all the staff an admin user.

Done!

**Review by andrew-kwon1 — DISMISSED** [review]
LGTM

**Comment by sanilkatula** [comment]
LGTM

**Comment by yuxiaolejs** [comment]
@pconrad Fixed: deployed on school dokku easily

**Comment by yuxiaolejs** [comment]
Moved to #46

**Pull request closed without merging**
