### PR TITLE
[feat] Swagger option on Navbar

### LINKED ISSUE #6: FEATURE: Swagger option on navbar
# User Story

* As a developer
* I can easily turn on the swagger option on the app navbar for any deployment through defining an environment variable `SHOW_SWAGGER_UI_LINK`
* so that it is easy to access swagger when I need it, but I can easily turn it off when I don't.

### Discussion

There is already code in the AppNavbar.js file that checks the value returned by /api/systemInfo for turning the Swagger link on and off.  But, at the moment, the resource file isn't set up to pull that value from an environment variable.

This PR shows what changes are needed to make this work:

https://github.com/ucsb-cs156/proj-courses/pull/93

Your job is just to make similar changes in this repo.

You could also make a similar issue that allows users to turn on/off the H2 console via a variable called `H2_CONSOLE_ENABLED`.  But it would be smart to do that in a separate PR so you get more points!

### Acceptance Criteria

As a developer
- [ ] When the config variable on dokku SHOW_SWAGGER_UI_LINK is set to true, the swagger link shows up
- [ ] When the config variable on dokku SHOW_SWAGGER_UI_LINK is set to false, the swagger link does NOT  show up.

### PR DESCRIPTION
**Pull request by andrew-kwon1**
User Story:
As a developer I can easily turn on the swagger option on the app navbar for any deployment through defining an environment variable SHOW_SWAGGER_UI_LINK so that it is easy to access swagger when I need it, but I can easily turn it off when I don't.

Allows developer to set a variable called SHOW_SWAGGER_UI_LINK to true or false in their config variables.
When set to true:
image

When set to false:
image

Closes #6

### CODE REVIEW

**Comment by sanilkatula** [comment]
Could you specify in detail what exactly you changed? And why was it necessary?

Make sure your PR is well constructed, with details of what you accomplished and what it might help to accomplish.

For example:-
if you are working on the backend and made api's. a storybook and link to swagger would be very helpful

and if you are working frontend, screenshots of how it looks and a deployment link would make the process of merging smoother.

If you have any questions and want to see some idle PR feel free to ask.

**Comment by andrew-kwon1** [comment]
In initial checks for the pull request, 12-backend-jacoco and 13-backend-inremental-pitest had this error:
Error:  JobsControllerTests.admin_can_launch_test_job_that_fails:221 » ConditionTimeout
even though on local, all tests passed. 
I rebuilt the jobs a few times and eventually passed, not sure what the issue was.

**Comment by sanilkatula** [comment]
LGTM

**Review by sanilkatula — APPROVED** [review]

**Comment by sanilkatula** [comment]
Ask someone from your team to review the PR than we can proceed with the merge.

**Review by yuxiaolejs — APPROVED** [review]
LGTM!

**Comment by yuxiaolejs** [comment]
> Ask someone from your team to review the PR than we can proceed with the merge.

Thanks!

**Pull request merged**
