### PR TITLE
Linked Course Show Page to be accessible from Courses Index Page

### PR DESCRIPTION
**Pull request by tmcanepa**
I added a hyperlink in my previous Course Show Page pull request which now can be seen working on the my dokku deployment app. When you have admin capabilities on the Course Index Page you should be able to create a course if there is not one already there and the id number should be a link which take you to the /course/{id #} page for the respective course.

https://organic-tmcanepa-dev.dokku-11.cs.ucsb.edu/

### CODE REVIEW

**Review by 30912hyl — CHANGES_REQUESTED** [review]
can you add me as admin for testing?

**Review by 30912hyl — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by Xalex217 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
